services:
  - type: web
    name: shopee-smart-cod-reliability
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt && python src/data_generator.py && python src/eda_analysis.py && python src/model_engine.py
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
