services:
  - type: web
    name: shopee-ultimate-case-challenge
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.18.0
